import { connectToDatabase } from '../lib/mongodb'

const sampleArticles = [
  {
    title: "The Future of Artificial Intelligence in Healthcare",
    excerpt: "Exploring how AI is revolutionizing medical diagnosis, treatment planning, and patient care in modern healthcare systems.",
    content: `
# The Future of Artificial Intelligence in Healthcare

Artificial Intelligence is transforming the healthcare industry at an unprecedented pace. From diagnostic imaging to drug discovery, AI is helping healthcare professionals make more accurate decisions and provide better patient care.

## Key Applications

### 1. Medical Imaging Analysis
AI-powered systems can analyze medical images with remarkable accuracy, helping radiologists detect abnormalities in X-rays, MRIs, and CT scans. These systems can identify patterns that might be missed by human eyes.

### 2. Predictive Analytics
Machine learning algorithms can analyze patient data to predict potential health issues before they become serious. This proactive approach to healthcare can save lives and reduce healthcare costs.

### 3. Drug Discovery
AI is accelerating the drug discovery process by analyzing vast amounts of molecular data to identify potential new treatments for various diseases.

## Challenges and Opportunities

While AI offers tremendous potential in healthcare, there are also significant challenges to address:

- Data privacy and security concerns
- Integration with existing healthcare systems
- Training healthcare professionals to work with AI
- Ensuring equitable access to AI-powered healthcare

## The Road Ahead

As AI technology continues to evolve, we can expect to see even more innovative applications in healthcare. The key will be to ensure that these technologies are developed and deployed in a way that benefits all patients, regardless of their socioeconomic status or geographic location.
    `,
    category: "Technology",
    status: "published",
    coverImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=1000&auto=format&fit=crop",
    tags: ["AI", "Healthcare", "Technology", "Future"],
    createdAt: new Date("2024-03-15"),
    updatedAt: new Date("2024-03-15"),
    publishedAt: new Date("2024-03-15"),
    readingTime: 5
  },
  {
    title: "Sustainable Living: A Guide to Reducing Your Carbon Footprint",
    excerpt: "Practical tips and strategies for living a more sustainable lifestyle and reducing your environmental impact.",
    content: `
# Sustainable Living: A Guide to Reducing Your Carbon Footprint

In today's world, sustainable living is more important than ever. This comprehensive guide will help you understand how to reduce your carbon footprint and live a more environmentally conscious life.

## Understanding Your Carbon Footprint

Your carbon footprint is the total amount of greenhouse gases that are generated by your actions. This includes everything from the energy you use at home to the food you eat and the transportation you choose.

## Practical Steps to Reduce Your Impact

### 1. Energy Conservation
- Switch to LED light bulbs
- Install a programmable thermostat
- Use energy-efficient appliances
- Consider solar panels for your home

### 2. Sustainable Transportation
- Walk or bike for short trips
- Use public transportation
- Consider an electric or hybrid vehicle
- Carpool when possible

### 3. Waste Reduction
- Reduce, reuse, and recycle
- Compost organic waste
- Avoid single-use plastics
- Buy in bulk to reduce packaging

### 4. Sustainable Diet
- Eat more plant-based meals
- Buy local and seasonal produce
- Reduce food waste
- Grow your own vegetables

## Making a Difference

Remember that every small action counts. By making conscious choices in your daily life, you can contribute to a more sustainable future for our planet.
    `,
    category: "Lifestyle",
    status: "published",
    coverImage: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?q=80&w=1000&auto=format&fit=crop",
    tags: ["Sustainability", "Environment", "Lifestyle", "Climate Change"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
    publishedAt: new Date("2024-03-10"),
    readingTime: 4
  },
  {
    title: "The Impact of Remote Work on Business Culture",
    excerpt: "Analyzing how the shift to remote work is reshaping workplace dynamics, communication, and company culture.",
    content: `
# The Impact of Remote Work on Business Culture

The COVID-19 pandemic has permanently changed the way we work. This article explores how remote work is transforming business culture and what companies need to do to adapt.

## The New Normal

Remote work has become a standard practice for many businesses, offering both opportunities and challenges for organizations and employees alike.

## Key Changes in Business Culture

### 1. Communication Patterns
- Increased use of digital communication tools
- More asynchronous communication
- Need for clear documentation
- Importance of virtual team building

### 2. Work-Life Balance
- Flexible working hours
- Blurred boundaries between work and personal life
- Need for better time management
- Importance of setting boundaries

### 3. Team Dynamics
- Virtual collaboration challenges
- Building trust in remote environments
- Maintaining team cohesion
- Managing remote performance

## Best Practices for Remote Work

### For Employers
- Invest in the right technology
- Establish clear communication guidelines
- Provide regular feedback and support
- Create virtual social opportunities

### For Employees
- Set up a dedicated workspace
- Maintain regular communication
- Take breaks and maintain work-life balance
- Stay connected with colleagues

## The Future of Work

As we move forward, hybrid work models are likely to become the norm, combining the benefits of remote work with the value of in-person collaboration.
    `,
    category: "Business",
    status: "review",
    coverImage: "https://images.unsplash.com/photo-1497215842964-222b430dc12f?q=80&w=1000&auto=format&fit=crop",
    tags: ["Remote Work", "Business", "Work Culture", "Future of Work"],
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
    readingTime: 6
  },
  {
    title: "Understanding Quantum Computing: A Beginner's Guide",
    excerpt: "An introduction to quantum computing concepts, applications, and its potential impact on technology.",
    content: `
# Understanding Quantum Computing: A Beginner's Guide

Quantum computing represents a fundamental shift in how we process information. This guide will help you understand the basics of quantum computing and its potential impact on our future.

## What is Quantum Computing?

Quantum computing harnesses the principles of quantum mechanics to perform calculations that would be impossible for classical computers. It uses quantum bits (qubits) instead of traditional binary bits.

## Key Concepts

### 1. Quantum Bits (Qubits)
Unlike classical bits that can be either 0 or 1, qubits can exist in multiple states simultaneously through superposition.

### 2. Quantum Entanglement
When qubits become entangled, the state of one qubit is directly related to the state of another, regardless of distance.

### 3. Quantum Interference
Quantum algorithms use interference to amplify correct solutions and cancel out incorrect ones.

## Applications

### Current Applications
- Cryptography
- Drug discovery
- Financial modeling
- Climate prediction

### Future Potential
- Artificial intelligence
- Material science
- Traffic optimization
- Weather forecasting

## Challenges and Limitations

- Maintaining qubit coherence
- Error correction
- Scalability
- Cost and accessibility

## The Road Ahead

While quantum computing is still in its early stages, it holds the potential to revolutionize fields from medicine to cryptography. Understanding these concepts is crucial for anyone interested in the future of technology.
    `,
    category: "Technology",
    status: "draft",
    coverImage: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1000&auto=format&fit=crop",
    tags: ["Quantum Computing", "Technology", "Future Tech", "Computing"],
    createdAt: new Date("2024-03-01"),
    updatedAt: new Date("2024-03-01"),
    readingTime: 7
  },
  {
    title: "The Science of Sleep: Understanding Your Sleep Cycle",
    excerpt: "Exploring the science behind sleep cycles, circadian rhythms, and tips for better sleep quality.",
    content: `
# The Science of Sleep: Understanding Your Sleep Cycle

Sleep is essential for our health and well-being, yet many of us don't understand how it works. This article explores the science of sleep and how to improve your sleep quality.

## Understanding Sleep Cycles

### The Stages of Sleep
1. N1 (Light Sleep)
2. N2 (True Sleep)
3. N3 (Deep Sleep)
4. REM Sleep

## The Role of Circadian Rhythms

Our body's internal clock regulates our sleep-wake cycle and influences various physiological processes throughout the day.

## Factors Affecting Sleep Quality

### 1. Environmental Factors
- Light exposure
- Temperature
- Noise levels
- Bedroom setup

### 2. Lifestyle Factors
- Exercise
- Diet
- Stress levels
- Screen time

### 3. Health Conditions
- Sleep disorders
- Mental health
- Physical health
- Medications

## Tips for Better Sleep

1. Maintain a consistent sleep schedule
2. Create a relaxing bedtime routine
3. Optimize your sleep environment
4. Limit exposure to blue light
5. Exercise regularly
6. Manage stress effectively

## The Impact of Poor Sleep

Chronic sleep deprivation can lead to:
- Impaired cognitive function
- Weakened immune system
- Increased risk of chronic diseases
- Mood disorders
- Weight gain

## Conclusion

Understanding and prioritizing sleep is crucial for maintaining good health and well-being. By implementing these strategies, you can improve your sleep quality and overall health.
    `,
    category: "Health",
    status: "published",
    coverImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1000&auto=format&fit=crop",
    tags: ["Sleep", "Health", "Wellness", "Science"],
    createdAt: new Date("2024-02-28"),
    updatedAt: new Date("2024-02-28"),
    publishedAt: new Date("2024-02-28"),
    readingTime: 5
  }
]

async function seedArticles() {
  try {
    const { db } = await connectToDatabase()
    
    // Clear existing articles
    await db.collection('articles').deleteMany({})
    
    // Insert sample articles
    const result = await db.collection('articles').insertMany(sampleArticles)
    
    console.log(`Successfully inserted ${result.insertedCount} articles`)
  } catch (error) {
    console.error('Error seeding articles:', error)
  }
}

seedArticles() 